services:
  - type: web
    name: quickmark-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add your other environment variables here, or set them in the Render dashboard
